name: Flatpak Release

on:
  pull_request:
    paths:
      - '.github/workflows/flatpak.yml'
  workflow_dispatch:

jobs:
  flatpak-build:
    runs-on: ubuntu-latest
    name: Flatpak Build
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add Submodules
        run: git submodule add https://github.com/flathub/shared-modules.git .github/flatpak/shared-modules
        
      - name: Install FlatPak dependencies
        run: |
          df -h
          mkdir -p out
          sudo apt-get update
          sudo apt-get install -y libc6 libplacebo librsvg2-dev patchelf flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y runtime/org.freedesktop.Platform/x86_64/24.08 runtime/org.freedesktop.Sdk/x86_64/24.08
          
      - name: Build Flatpak
        run: flatpak-builder --repo=local ./out .github/flatpak/com.unicornsonlsd.finamp.yml
            
      - name: Build Flatpak Bundle
        run: flatpak build-bundle local com.unicornsonlsd.finamp.flatpak com.unicornsonlsd.finamp

      - name: Upload Flatpak Bundle
        uses: actions/upload-artifact@v4
        with:
          name: com.unicornsonlsd.finamp.flatpak
          path: ./com.unicornsonlsd.finamp.flatpak